---
- hosts: dockerhost

 tasks:
 - name: stop existing container
   command: dockerstop regapp-server
   ignore_errors: yes
   
 - name: remove the container
   command: docker rm regapp-server
   ignore_errors: yes
   
 - name: remove image
   command: docker rmi jmartinezl/regapp:latest
   ignore_errors: yes
 
 - name: create container
   command: docke run -d --name regapp-server -p 8082:8080 jmartinezl/regapp:latest
